"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class DavisImu(object):
    __slots__ = ["clock_usec", "accel", "temperature", "gyro"]

    def __init__(self):
        self.clock_usec = 0
        self.accel = [ 0.0 for dim0 in range(3) ]
        self.temperature = 0.0
        self.gyro = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(DavisImu._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.clock_usec))
        buf.write(struct.pack('>3f', *self.accel[:3]))
        buf.write(struct.pack(">f", self.temperature))
        buf.write(struct.pack('>3f', *self.gyro[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != DavisImu._get_packed_fingerprint():
            raise ValueError("Decode error")
        return DavisImu._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = DavisImu()
        self.clock_usec = struct.unpack(">i", buf.read(4))[0]
        self.accel = struct.unpack('>3f', buf.read(12))
        self.temperature = struct.unpack(">f", buf.read(4))[0]
        self.gyro = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if DavisImu in parents: return 0
        tmphash = (0x4ba65373abd0a8c0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if DavisImu._packed_fingerprint is None:
            DavisImu._packed_fingerprint = struct.pack(">Q", DavisImu._get_hash_recursive([]))
        return DavisImu._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

