// code by mg
package ch.ethz.idsc.demo.mg.slam;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.util.stream.IntStream;

import ch.ethz.idsc.demo.mg.util.VisualizationUtil;
import ch.ethz.idsc.tensor.Tensor;

// gives an image of the maps generated by the SLAM algorithm
public class SlamMapFrame {
  private static final byte CLEAR_BYTE = (byte) 255;
  private final BufferedImage bufferedImage;
  private final Graphics2D graphics;
  private final byte[] bytes;
  private final double cornerX;
  private final double cornerY;
  private final double cellDim;
  private final int kartLength;
  private final int frameWidth;
  private final int frameHeight;
  private final int numberOfCells;
  private double[] mapArray;
  private double maxValue;

  SlamMapFrame(SlamConfig slamConfig) {
    frameWidth = slamConfig.dimX.divide(slamConfig.cellDim).number().intValue();
    frameHeight = slamConfig.dimY.divide(slamConfig.cellDim).number().intValue();
    numberOfCells = frameWidth * frameHeight;
    cornerX = slamConfig.corner.Get(0).number().doubleValue();
    cornerY = slamConfig.corner.Get(1).number().doubleValue();
    cellDim = slamConfig.cellDim.number().doubleValue();
    kartLength = (int) (slamConfig.kartSize.number().doubleValue() / cellDim);
    mapArray = new double[numberOfCells];
    bufferedImage = new BufferedImage(frameWidth, frameHeight, BufferedImage.TYPE_BYTE_INDEXED);
    graphics = bufferedImage.createGraphics();
    DataBufferByte dataBufferByte = (DataBufferByte) bufferedImage.getRaster().getDataBuffer();
    bytes = dataBufferByte.getData();
  }

  public void setMap(MapProvider map) {
    // safety check
    if (map.getNumberOfCells() != numberOfCells)
      System.out.println("Fatal: something went wrong!");
    else {
      mapArray = map.getMapArray();
      maxValue = map.getMaxValue();
      paintFrame();
    }
  }

  // draws the frame according to the mapArray values. values are normalized by maxValue
  private void paintFrame() {
    if (maxValue == 0)
      IntStream.range(0, bytes.length).forEach(i -> bytes[i] = CLEAR_BYTE);
    else {
      for (int i = 0; i < bytes.length; i++) {
        bytes[i] = (byte) (216 + 39 * (1 - mapArray[i] / maxValue));
      }
    }
  }

  public void addGokartPose(Tensor pose, Color color) {
    double posX = pose.Get(0).number().doubleValue();
    double posY = pose.Get(1).number().doubleValue();
    double rotAngle = pose.Get(2).number().doubleValue();
    // get pixelPos
    int pixelPoseX = (int) ((posX - cornerX) / cellDim);
    int pixelPoseY = (int) ((posY - cornerY) / cellDim);
    // draw ellipse at go kart position
    Ellipse2D ellipse = new Ellipse2D.Float(pixelPoseX - kartLength / 2, pixelPoseY - kartLength / 4, kartLength, kartLength / 2);
    AffineTransform old = graphics.getTransform();
    graphics.rotate(rotAngle, pixelPoseX, pixelPoseY);
    graphics.setColor(color);
    graphics.draw(ellipse);
    graphics.fill(ellipse);
    graphics.setTransform(old);
  }

  // return flipped image such that x axis points right and y axis upwards
  public BufferedImage getFrame() {
    return VisualizationUtil.flipHorizontal(bufferedImage);
  }
}
