// code by jph
package ch.ethz.idsc.retina.dev.velodyne;

/** events generated by lidar */
public class LidarSpacialEvent {
  /** timestamp of event in [us] */
  public final int usec;
  /** spacial coordinates in [m] */
  public final float[] coords; // x,y,z
  /** intensity of reflection [0, 1, ..., 255]
   * 255 == most intensive return */
  public final int intensity;

  public LidarSpacialEvent(int usec, float[] coords, int intensity) {
    this.usec = usec;
    this.coords = coords;
    this.intensity = intensity;
  }
}
