// code by jph, gjoel
package ch.ethz.idsc.retina.lidar;

/** events generated by lidar */
/* package */ abstract class LidarSpacialEvent {
  /** timestamp of event in [us] */
  public final int usec;
  /** spacial coordinates */
  public final float[] coords;
  /** intensity of reflection [0, 1, ..., 255] 255 == most intensive return */
  public final byte intensity;

  public LidarSpacialEvent(int usec, float[] coords, byte intensity) {
    this.usec = usec;
    this.coords = coords;
    this.intensity = intensity;
  }
}
