// code by jph, gjoel
package ch.ethz.idsc.retina.lidar;

import ch.ethz.idsc.tensor.Tensor;
import ch.ethz.idsc.tensor.Tensors;

/** events generated by lidar */
public class LidarXYZEvent {
  /** timestamp of event in [us] */
  public final int usec;
  /** spacial coordinates */
  // TODO JPH prevent public access to coords
  public final float[] coords;
  /** intensity of reflection [0, 1, ..., 255] 255 == most intensive return */
  public final byte intensity;

  /** @param usec timestamp of event in [us]
   * @param coords spacial coordinates in [m] when coords.length == 3 then coordinates are x, y, z
   * when coords.length == 2 then coordinates are x, y
   * @param intensity intensity of reflection [0, 1, ..., 255] 255 == most intensive return */
  public LidarXYZEvent(int usec, float[] coords, byte intensity) {
    this.usec = usec;
    this.coords = coords;
    this.intensity = intensity;
  }

  public Tensor getXY() {
    return Tensors.vector(coords[0], coords[1]);
  }
}
