// code by jph, gjoel
package ch.ethz.idsc.retina.lidar;

import ch.ethz.idsc.tensor.RealScalar;
import ch.ethz.idsc.tensor.Scalar;

/** events generated by lidar */
public class LidarPolarEvent extends LidarSpacialEvent {
  /** @param usec timestamp of event in [us]
   * @param coords spacial coordinates in [rad] (azimuth, elevation) resp. [m] (distance)
   * @param intensity intensity of reflection [0, 1, ..., 255] 255 == most intensive return */
  public LidarPolarEvent(int usec, float[] coords, byte intensity) {
    super(usec, coords, intensity);
  }

  public Scalar getAzimuth() {
    return RealScalar.of(coords[0]);
  }

  public Scalar getElevation() {
    return RealScalar.of(coords[1]);
  }

  public Scalar getDistance() {
    return RealScalar.of(coords[2]);
  }
}
